export const defaultOptions = {
  padding: {
    bottom: 10,
    left: 10,
    right: 10,
    top: 10,
  },
  waterMarker: {
    enable: true,
    text: '',
    textMaxLen: 14,
    fontSize: 30,
    cellWidth: 160,
    cellHeight: 140,
    rotateDeg: (-30 * Math.PI) / 180,
    fontWeight: 'normal',
    fontFamily: 'Helvetica Neue,PingFang SC,Microsoft YaHei,Arial,sans-serif',
    textAlign: 'center',
    color: 'rgba(0,0,0,.04)',
    separate: true,
    textBaseline: 'middle',
    textPosX: 30,
    textPosY: 100,
  },
  head: {
    fix: true,
    fontSize: 14,
    fontWeight: 'bold',
    fontFamily: 'Helvetica Neue,PingFang SC,Microsoft YaHei,Arial,sans-serif',
    color: '#515a6e',
    lineHeight: 1.2,
    backgroundColor: '#F8F8F9',
    padding: {
      bottom: 10,
      left: 10,
      right: 10,
      top: 10,
    },
    textAlign: 'center',
  },
  cell: {
    fontSize: 14,
    fontWeight: 'normal',
    fontFamily: 'Helvetica Neue,PingFang SC,Microsoft YaHei,Arial,sans-serif',
    color: '#515a6e',
    lineHeight: 1.2,
    padding: {
      bottom: 10,
      left: 0,
      right: 20,
      top: 10,
    },
    textAlign: 'center',
  },
  column: {
    width: 100,
    maxWidth: 260,
    adjust: true,
  },
  borderColor: '#E8EAEC',
  borderWidth: 1,
  stripe: true,
  stripeColor: 'rgba(230,230,230,.1)',
  showTextTip: true,
  textOverTip: true,
  fit: false,
  sort: true,
};
